default:
  postgres:
    dbname: "workout"
    host: "localhost"
    port: 5432
    user: "jyh"
    password: "Zpflrjs94!"
    
shinyapps:
  postgres:
    dbname: "workout"
    host: "127.0.0.1"
    port: 5432
    user: "postgres"
    password: "postgres"
    
